version: "3"
services:
  webserver:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./websites:/usr/share/nginx/html
    depends_on:
      - db
    links:
      - db
  db:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db_vol:/var/lib/mysql
    ports:
      - '3306:3306'
    expose:
      - '3306'
volumes:
  db_vol:

